SELECT COUNT(*)
FROM Tracks;

SELECT genre_id, COUNT(*)
FROM Tracks 
GROUP BY album_id;

SELECT genre_id, MIN(duration_ms) AS "Average duration"
FROM Tracks 
GROUP BY genre_id;

--COUNT THE NUMBER OF OBJECT FROM A TABLE OR SEPCIFI CREQUIREMENT FROM A TABLE
--ONLY COUNTS NUMBER O FENTITIES WITHIN THAT GENRE_ID
--ADDS THE AVERAGE DURAITON IN TABLE NECT TO GENRE ID

SELECT album_id, SUM(duration_ms)
FROM Tracks;

SELECT album_id, AVG(duration_ms)
FROM Tracks
GROUP BY album_id
ORDER BY AVG(duration_ms) DESC
LIMIT 1;
